# Two-D Arrays

In [8]:
import numpy as np

# Create a 3x3 array
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Now you can access elements, e.g.:
print(A[0][0])  # Output: 1
print(A[1][2])  # Output: 6

# If you want a regular Python list that contains the same rows as A
a = [
    [A[0][0], A[0][1], A[0][2]],
    [A[1][0], A[1][1], A[1][2]],
    [A[2][0], A[2][1], A[2][2]]
]


1
6


In [9]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a

[[np.int64(1), np.int64(2), np.int64(3)],
 [np.int64(4), np.int64(5), np.int64(6)],
 [np.int64(7), np.int64(8), np.int64(9)]]

In [12]:
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

In [13]:
# --------------------------
# Slicing
# --------------------------
# Extract first two rows and first two columns
slice_A = A[:2, :2]  # [[1, 2], [4, 5]]

# Extract last row
last_row = A[-1, :]  # [7, 8, 9]

# Extract second column
second_col = A[:, 1]  # [2, 5, 8]

# --------------------------
# Arithmetic operations (element-wise)
# --------------------------
add = A + B           # Addition
subtract = A - B      # Subtraction
multiply = A * B      # Element-wise multiplication
divide = A / B        # Element-wise division (watch divide by zero)

# Scalar operations
add_scalar = A + 10
multiply_scalar = A * 3

# --------------------------
# Dot product and matrix operations
# --------------------------
# Dot product of two vectors
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
dot_product = np.dot(vec1, vec2)  # 1*4 + 2*5 + 3*6 = 32

# Matrix multiplication
mat_mult = np.dot(A, B)  # 3x3 matrix result

# Another way using operator @ (Python 3.5+)
mat_mult_2 = A @ B

# --------------------------
# Other useful functions
# --------------------------
# Transpose
A_T = A.T

# Sum of all elements
total_sum = A.sum()

# Sum by axis
sum_by_row = A.sum(axis=1)     # Sum of each row
sum_by_col = A.sum(axis=0)     # Sum of each column

# Mean of all elements
mean_val = A.mean()

# Element-wise square root
sqrt_A = np.sqrt(A)

# --------------------------
# Print Outputs (optional)
# --------------------------
print("Slice of A:\n", slice_A)
print("Dot product of vec1 and vec2:", dot_product)
print("Matrix multiplication result:\n", mat_mult)
print("Sum by row:", sum_by_row)
print("Square root of A:\n", sqrt_A)

Slice of A:
 [[1 2]
 [4 5]]
Dot product of vec1 and vec2: 32
Matrix multiplication result:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Sum by row: [ 6 15 24]
Square root of A:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
